namespace BootstrapMvcHelperExtensions
{
    /// <summary>
    /// Button Types, determines the coloring/effects
    /// </summary>
    public enum ButtonType
    {
        @default,
        primary,
        info,
        success,
        warning,
        danger
    }

    /// <summary>
    /// Button Sizes, determines the heigh, width and text size
    /// </summary>
    public enum ButtonSize
    {
        @default,
        large,
        small
    }

    /// <summary>
    /// Input sizes, determines the width of the input
    /// </summary>
    public enum InputSize
    {
        small,
        medium,
        large
    }

    /// <summary>
    /// Glyph Icons
    /// </summary>
    public enum Icon
    {
        @default,
        icon_glass,
        icon_music,
        icon_search,
        icon_envelope,
        icon_heart,
        icon_star,
        icon_star_empty,
        icon_user,
        icon_film,
        icon_th_large,
        icon_th,
        icon_th_list,
        icon_ok,
        icon_remove,
        icon_zoom_in,
        icon_zoom_out,
        icon_off,
        icon_signal,
        icon_cog,
        icon_trash,
        icon_home,
        icon_file,
        icon_time,
        icon_road,
        icon_download_alt,
        icon_download,
        icon_upload,
        icon_inbox,
        icon_play_circle,
        icon_repeat,
        icon_refresh,
        icon_list_alt,
        icon_lock,
        icon_flag,
        icon_headphones,
        icon_volume_off,
        icon_volume_down,
        icon_volume_up,
        icon_qrcode,
        icon_barcode,
        icon_tag,
        icon_tags,
        icon_book,
        icon_bookmark,
        icon_print,
        icon_camera,
        icon_font,
        icon_bold,
        icon_italic,
        icon_text_height,
        icon_text_width,
        icon_align_left,
        icon_align_center,
        icon_align_right,
        icon_align_justify,
        icon_list,
        icon_indent_left,
        icon_indent_right,
        icon_facetime_video,
        icon_picture,
        icon_pencil,
        icon_map_marker,
        icon_adjust,
        icon_tint,
        icon_edit,
        icon_share,
        icon_check,
        icon_move,
        icon_step_backward,
        icon_fast_backward,
        icon_backward,
        icon_play,
        icon_pause,
        icon_stop,
        icon_forward,
        icon_fast_forward,
        icon_step_forward,
        icon_eject,
        icon_chevron_left,
        icon_chevron_right,
        icon_plus_sign,
        icon_minus_sign,
        icon_remove_sign,
        icon_ok_sign,
        icon_question_sign,
        icon_info_sign,
        icon_screenshot,
        icon_remove_circle,
        icon_ok_circle,
        icon_ban_circle,
        icon_arrow_left,
        icon_arrow_right,
        icon_arrow_up,
        icon_arrow_down,
        icon_share_alt,
        icon_resize_full,
        icon_resize_small,
        icon_plus,
        icon_minus,
        icon_asterisk,
        icon_exclamation_sign,
        icon_gift,
        icon_leaf,
        icon_fire,
        icon_eye_open,
        icon_eye_close,
        icon_warning_sign,
        icon_plane,
        icon_calendar,
        icon_random,
        icon_comment,
        icon_magnet,
        icon_chevron_up,
        icon_chevron_down,
        icon_retweet,
        icon_shopping_cart,
        icon_folder_close,
        icon_folder_open,
        icon_resize_vertical,
        icon_resize_horizontal,
        icon_hdd,
        icon_bullhorn,
        icon_bell,
        icon_certificate,
        icon_thumbs_up,
        icon_thumbs_down,
        icon_hand_right,
        icon_hand_left,
        icon_hand_up,
        icon_hand_down,
        icon_circle_arrow_right,
        icon_circle_arrow_left,
        icon_circle_arrow_up,
        icon_circle_arrow_down,
        icon_globe,
        icon_wrench,
        icon_tasks,
        icon_filter,
        icon_briefcase,
        icon_fullscreen    
    }
}
